### ISSUE TITLE
引入 ant-design-vue 二次开发的组件库，组件库中的自定义 hooks 会报错

### ISSUE THREAD

**Issue by az031120103** [xinlei3166/vitepress-theme-demoblock#39]
**开发环境信息**
macOS monterey 12.6
node 16.11.0
ant-design-vue 3.2.11

**最小化重现**
https://github.com/az031120103/test

**复现步骤**
git clone https://github.com/az031120103/test.git
npm run dev:ui
npm run dev:docs

**实际发生**
Form 组件的自定义 hooks useConfigInject 报错：

useConfigInject.js:71 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getPrefixCls')
at __WEBPACK_DEFAULT_EXPORT__ (useConfigInject.js:71:1)
at setup (Form.js:118:43)
at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
at setupStatefulComponent (runtime-core.esm-bundler.js:7246:29)
at setupComponent (runtime-core.esm-bundler.js:7201:11)
at mountComponent (runtime-core.esm-bundler.js:5524:13)
at processComponent (runtime-core.esm-bundler.js:5499:17)
at patch (runtime-core.esm-bundler.js:5101:21)
at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5638:21)
at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)

**Comment by xinlei3166** [comment]
`v3.0.0` 版本改为使用 `vite` 插件方式支持部分功能，你可以试用下。

`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
